# Site settings
title: DCU BS Data Science DCU123
email: 
description: > # this means to ignore newlines until "baseurl:"
Website for the DCU BS in Data Science
baseurl: "" # the subpath of your site, e.g. /blog/
url: "DataScienceDCU.github.io" # the base hostname & protocol for your site

# User setting
owner: DCU School of Computing
email: 
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
