# Site settings
title: DCU BS Data Science DCU123
email: 
description: > # this means to ignore newlines until "baseurl:"
  DCU BS Data Science
baseurl: "" # the subpath of your site, e.g. /blog/
url: "DataScienceDCU.github.io" # the base hostname & protocol for your site

# User setting
owner: DCU School of Computing
email: marketing@computing.dcu.ie
facebook_username: datasciencedcu
twitter_username: datasciencedcu
github_username: DataScienceDCU
address:
  - line: "School of Computing"
  - line: "Dublin City University," 
  - line: "Glasnevin, Dublin 9, Ireland"
  # Feel free to add more lines here 
telephone: "+353-1-7008980" 
copyright: "DCU School of Computing"

# API settings
google_api_key:

# Build settings
markdown: kramdown
